name: Deploy docs

description: build and deloy docs to netlify

inputs
  github-token:
    required: true
  netlify-auth-token:
    required: true
  netlify-side-id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        pnpm docs:build

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './docs/.vitepress/dist'
        production-branch: main
        github-token: ${{ inputs.github-token }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify-auth-token }}
        NETLIFY_SITE_ID: ${{ inputs.netlify-side-id }}
