name: Action 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Here goes the shared code

      - name: Run script specific to action 1
        run: echo "this is action 1"
