name: Action 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/shared_code.yml  # Reference to shared code

      # Here goes the shared code

      - name: Run script specific to action 1
        run: echo "this is action 1"
