name: Build

on:
  push:
    branches: ['main']
    paths-ignore: ['docs/**/*']

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set pnpm enveronment
        uses: ./.github/workflows/common/pnpm

      - name: Build
        run: |
          pnpm build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ vars.GH_TOKEN }}
          NPM_TOKEN: ${{ vars.NPM_TOKEN }}
          # @see https://typicode.github.io/husky/how-to.html#ci-server-and-docker
          HUSKY: 0
        run: |
          pnpm run release

      - name: Generate type docs
        run: |
          pnpm docs:typedoc

      # - name: deploy docs
      #   uses: ./.github/workflows/deploy-docs
