name: 📦 Build

on:
  push:
    paths-ignore: ['docs/**/*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set pnpm environment
        uses: ./.github/workflows/common/pnpm

      - name: Build
        run: |
          pnpm build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # @see https://typicode.github.io/husky/how-to.html#ci-server-and-docker
          HUSKY: 0
        run: |
          pnpm run release

      - name: Generate type docs
        run: |
          pnpm docs:typedoc

      - name: Deploy to Netlify
        uses: ./.github/workflows/common/deploy-docs
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-side-id: ${{ vars.NETLIFY_SITE_ID }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ljtang2009/lint-use
