on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set pnpm version
        uses: pnpm/action-setup@v3
        with:
          version: 'latest'
          run_install: false

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install
        run: |
          pnpm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ vars.GH_TOKEN }}
          NPM_TOKEN: ${{ vars.NPM_TOKEN }}
          # @see https://typicode.github.io/husky/how-to.html#ci-server-and-docker
          HUSKY: 0
        run: |
          pnpm run release
