name: 📗 Deploy Docs

on:
  push:
    branches: ['main']
    paths: ['docs/**/*']
  pull_request:
    branches: ['main']
    paths: ['docs/**/*']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set pnpm environment
        uses: ./.github/workflows/common/pnpm

      - name: Deploy to Netlify
        uses: ./.github/workflows/common/deploy-docs
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-side-id: ${{ vars.NETLIFY_SITE_ID }}
