name: Deploy Docs

on:
  push:
    branches: ['main']
    paths: ['docs/**/*']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set pnpm enveronment
        uses: ./.github/workflows/common/pnpm

      - name: Deploy to Netlify
        uses: ./.github/workflows/common/deploy-docs

      # - name: Build
      #   run: |
      #     pnpm docs:build

      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v3.0
      #   with:
      #     publish-dir: './docs/.vitepress/dist'
      #     production-branch: main
      #     github-token: ${{ secrets.GH_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
